#pragma kernel Main

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "../Shared/Defines.hlsl"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

RWByteAddressBuffer ProbeCountsRW;

RWBuffer<uint> ArgumentsRW;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

[numthreads(1, 1, 1)]
void Main(in uint3 dispatch_thread_id : SV_DispatchThreadID)
{
    uint count = min(ProbeCountsRW.Load(PROBE_COUNT_ENTRY * 4), PROBE_MAX_ENTRIES);

    ArgumentsRW[0] = count;
    ArgumentsRW[1] = 1;
    ArgumentsRW[2] = 1;
    ArgumentsRW[3] = 0;

    ArgumentsRW[4] = count * GROUPS_PER_PROBE;
    ArgumentsRW[5] = 1;
    ArgumentsRW[6] = 1;
    ArgumentsRW[7] = 0;

    ArgumentsRW[8]  = (count + GROUP - 1) / GROUP;
    ArgumentsRW[9]  = 1;
    ArgumentsRW[10] = 1;
    ArgumentsRW[11] = 0;

    ProbeCountsRW.Store(PROBE_COUNT_TEMP * 4, 0);
}