#pragma kernel Main

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "../Shared/Defines.hlsl"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ByteAddressBuffer ProbeCounts;

RWByteAddressBuffer ProbeArraysRW;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

[numthreads(GROUP, 1, 1)]
void Main(in uint3 dispatch_thread_id : SV_DispatchThreadID)
{
	uint index = dispatch_thread_id.x;

	[branch]
	if (index < ProbeCounts.Load(PROBE_COUNT_REMOVE * 4))
	{
		uint entry_index = ProbeArraysRW.Load((PROBE_ARRAY_REMOVE + index) * 4);

		uint cursor = ProbeCounts.Load(PROBE_COUNT_POOL * 4);
		ProbeArraysRW.Store((PROBE_ARRAY_POOL + cursor + index) * 4, entry_index);
	}
}