#pragma kernel Main

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "Flip.hlsl"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

uint3 Resolution;
float Distance;
float SplatThreshold;

ByteAddressBuffer Positive;

RWByteAddressBuffer BufferRW;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

[numthreads(8, 8, 8)]
void Main(in uint3 dispatch_thread_id : SV_DispatchThreadID)
{
	uint3 coord = dispatch_thread_id;

	[branch]
	if (all(coord < Resolution))
	{
		uint index = coord.x + coord.y * Resolution.x + coord.z * Resolution.x * Resolution.y;

		uint value = BufferRW.Load(index * 4);
		uint positive = Positive.Load(index * 4);

		float d = asfloat(unrotateSign(value));

		if (positive > 0 && d < -SplatThreshold * 0.54)
			d = abs(d);

		BufferRW.Store(index * 4, asuint(d));
	}
}