#pragma kernel Main

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "../Shared/Defines.hlsl"

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ByteAddressBuffer SurfelCounts;
ByteAddressBuffer SurfelEntries;

RWByteAddressBuffer SurfelArraysRW;
RWByteAddressBuffer SurfelGridRW;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

[numthreads(GROUP, 1, 1)]
void Main(in uint3 dispatch_thread_id : SV_DispatchThreadID)
{
	uint index = dispatch_thread_id.x;

	[branch]
	if (index < SurfelCounts.Load(SURFEL_COUNT_ENTRY * 4))
	{
		uint entry_index = SurfelArraysRW.Load((SURFEL_ARRAY_TEMP + index) * 4);
		SurfelArraysRW.Store((SURFEL_ARRAY_ENTRY + index) * 4, entry_index);

		uint cell_index = SurfelEntries.Load(entry_index * SURFEL_ENTRY_STRIDE + SURFEL_ENTRY_CELL) & UNFLAG;

		// all surfels move by the same offset, so there shouldn't be any contention
		SurfelGridRW.Store(cell_index * 4, entry_index);
	}
}